stages:
  - test
  - deploy

before_script:
  - apt update -qy
  - apt upgrade -qy

python3:
  stage: test
  image: python:latest
  script:
    - pip install pre-commit pytest
    - pre-commit run --all-files

package_only:
  stage: deploy
  image: python:latest
  script:
  - make package
  except:
    - master

package_and_deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install twine
  - make package
  - make deploy
  after_script:
  - rm -vf ~/.pypirc
  only:
    - master
