variables:
    PYPI_USER: SECURE
    PYPI_PASSWORD: SECURE

stages:
  - test
  - deploy

before_script:
  - apt update -qy
  - apt upgrade -qy
  - apt install -qy pandoc

python2:
  stage: test
  image: python:2
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py2

python3:
  stage: test
  image: python:3
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py3

deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install pypandoc twine
  - python setup.py check sdist bdist_wheel
  - sed -e "s/PYPI_USER/$PYPI_USER/g" -e "s/PYPI_PASSWORD/$PYPI_PASSWORD/g" .pypirc >> ~/.pypirc
  - twine upload -r pypitest dist/GPM-Playlist-Generator-*.tar.gz dist/GPM_Playlist_Generator-*.whl
  after_script:
  - rm -vf ~/.pypirc
