stages:
  - test
  - deploy

before_script:
  - apt update -qy
  - apt upgrade -qy
  - apt install -qy pandoc

python2:
  stage: test
  image: python:2
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py2

python3:
  stage: test
  image: python:3
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py3

# deploy_test:
#   stage: deploy
#   image: python:latest
#   script:
#   - pip install pypandoc twine
#   - python setup.py check sdist bdist_wheel
#   - make ~/.pypirc
#   - twine upload -r pypitest dist/GPM-Playlist-Generator-*.tar.gz dist/GPM_Playlist_Generator-*.whl
#   after_script:
#   - rm -vf ~/.pypirc 
#   except:
#     - master

deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install pypandoc twine
  - python setup.py check sdist bdist_wheel
  - make ~/.pypirc
  - twine upload dist/GPM-Playlist-Generator-*.tar.gz dist/GPM_Playlist_Generator-*.whl
  after_script:
  - rm -vf ~/.pypirc
  only:
    - master
