stages:
  - test
  - deploy

before_script:
  - apt update -qy
  - apt upgrade -qy

python3:
  stage: test
  image: python:3
  script:
    - pip install tox bandit
    - make test TOXENVLIST=py3

package_only:
  stage: deploy
  image: python:latest
  script:
  - make package
  except:
    - master

package_and_deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install twine
  - make package
  - make deploy
  after_script:
  - rm -vf ~/.pypirc
  only:
    - master
