stages:
  - test
  - deploy

before_script:
  - apt update -qy
  - apt upgrade -qy
  - apt install -qy pandoc

python2:
  stage: test
  image: python:2
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py2

python3:
  stage: test
  image: python:3
  script:
    - pip install pypandoc tox bandit
    - make test TOXENVLIST=py3

package_only:
  stage: deploy
  image: python:latest
  script:
  - pip install pypandoc
  - make package
  except:
    - master

package_and_deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install pypandoc twine
  - make package
  - make deploy
  after_script:
  - rm -vf ~/.pypirc
  only:
    - master
